#!/usr/bin/env bash
# archive.sh — Archive LevelGen v1 scripts to .cs.bak in _Archive folder.
#
# WHAT THIS DOES:
#   1. Creates Assets/Scripts/_Archive/ mirroring the old folder layout
#   2. Moves archived .cs files into _Archive/ with .cs.bak extension
#   3. Also moves the matching .cs.meta files (Unity pairs them)
#   4. KEEPS: ExitPoint.cs, RoomPiece.cs, PieceCatalogue.cs, PieceEntry.cs
#            (if present), PieceCatalogueEditor.cs, LVL_Configurator.cs,
#            WhiteboxPackFactory.cs in their original locations
#   5. Generates unarchive.sh alongside this script for easy rollback
#
# HOW TO USE:
#   From your Unity project root (where Assets/ lives):
#     bash archive.sh
#
# TO RESTORE:
#   bash unarchive.sh
#
# SAFETY:
#   - Prints every action before doing it
#   - Skips files that don't exist instead of erroring
#   - Never touches files outside the archive list
#   - Creates a log at archive.log with timestamps

set -e
LOG="$(pwd)/archive.log"
ARCHIVE_ROOT="Assets/Scripts/_Archive"
UNARCHIVE_SCRIPT="unarchive.sh"

# Files to archive (relative to project root). KEEP list is NOT here.
FILES_TO_ARCHIVE=(
  "Assets/Scripts/Data/LevelSequence.cs"
  "Assets/Scripts/Data/SeedData.cs"
  "Assets/Scripts/Editor/LevelGeneratorEditor.cs"
  "Assets/Scripts/Editor/LevelGenSetup.cs"
  "Assets/Scripts/Editor/PlaceholderPrefabFactory.cs"
  "Assets/Scripts/Editor/RoomWorkshopWindow.cs"
  "Assets/Scripts/Generation/BoundsChecker.cs"
  "Assets/Scripts/Generation/LevelGenerator.cs"
  "Assets/Scripts/Workshop/PropCatalogue.cs"
  "Assets/Scripts/Workshop/PropEntry.cs"
  "Assets/Scripts/Workshop/RoomBuilder.cs"
  "Assets/Scripts/Workshop/RoomContentGenerator.cs"
  "Assets/Scripts/Workshop/RoomDefinition.cs"
  "Assets/Scripts/Workshop/RoomPreset.cs"
  "Assets/Scripts/Workshop/RoomPresetLibrary.cs"
  "Assets/Scripts/Workshop/SpawnPoint.cs"
)

echo "LevelGen v1 Archive — $(date)" | tee "$LOG"
echo "Working dir: $(pwd)" | tee -a "$LOG"
echo "" | tee -a "$LOG"

# Sanity check: must be run from project root
if [ ! -d "Assets/Scripts" ]; then
  echo "ERROR: Assets/Scripts not found. Run this from your Unity project root." | tee -a "$LOG"
  exit 1
fi

# Create archive tree
echo "Creating archive folders..." | tee -a "$LOG"
mkdir -p "$ARCHIVE_ROOT/Data"
mkdir -p "$ARCHIVE_ROOT/Editor"
mkdir -p "$ARCHIVE_ROOT/Generation"
mkdir -p "$ARCHIVE_ROOT/Workshop"
echo "  $ARCHIVE_ROOT/{Data,Editor,Generation,Workshop} ready" | tee -a "$LOG"
echo "" | tee -a "$LOG"

# Start building the unarchive script
cat > "$UNARCHIVE_SCRIPT" <<EOF
#!/usr/bin/env bash
# unarchive.sh — Restore LevelGen v1 scripts from _Archive back to original locations.
# Auto-generated by archive.sh on $(date)
set -e
EOF
chmod +x "$UNARCHIVE_SCRIPT"

archived=0
skipped=0

for src in "${FILES_TO_ARCHIVE[@]}"; do
  if [ ! -f "$src" ]; then
    echo "SKIP   $src  (not present)" | tee -a "$LOG"
    skipped=$((skipped + 1))
    continue
  fi

  # Derive archive path: Assets/Scripts/Foo/Bar.cs -> Assets/Scripts/_Archive/Foo/Bar.cs.bak
  relative="${src#Assets/Scripts/}"
  dst="$ARCHIVE_ROOT/${relative}.bak"

  # Move the .cs file
  echo "MOVE   $src"
  echo "  ->   $dst" | tee -a "$LOG"
  mv "$src" "$dst"

  # Move the .cs.meta file if present (Unity pairs them)
  if [ -f "${src}.meta" ]; then
    mv "${src}.meta" "${dst}.meta"
    echo "  +    ${src}.meta -> ${dst}.meta" | tee -a "$LOG"
  fi

  # Append restore instruction to unarchive.sh
  echo "mv \"$dst\" \"$src\"" >> "$UNARCHIVE_SCRIPT"
  if [ -f "${dst}.meta" ]; then
    echo "mv \"${dst}.meta\" \"${src}.meta\"" >> "$UNARCHIVE_SCRIPT"
  fi

  archived=$((archived + 1))
done

# Finish the unarchive script
cat >> "$UNARCHIVE_SCRIPT" <<'EOF'
echo "Restore complete. Let Unity recompile, then delete _Archive if desired."
EOF

echo "" | tee -a "$LOG"
echo "Archived: $archived" | tee -a "$LOG"
echo "Skipped:  $skipped" | tee -a "$LOG"
echo "" | tee -a "$LOG"
echo "KEPT in place (referenced by new code):" | tee -a "$LOG"
echo "  Assets/Scripts/Generation/ExitPoint.cs" | tee -a "$LOG"
echo "  Assets/Scripts/Generation/RoomPiece.cs" | tee -a "$LOG"
echo "  Assets/Scripts/Workshop/PieceCatalogue.cs" | tee -a "$LOG"
echo "  Assets/Scripts/Editor/PieceCatalogueEditor.cs" | tee -a "$LOG"
echo "  Assets/Scripts/Editor/LVL_Configurator.cs" | tee -a "$LOG"
echo "  Assets/Scripts/Editor/WhiteboxPackFactory.cs" | tee -a "$LOG"
echo "" | tee -a "$LOG"
echo "Restore script created: $UNARCHIVE_SCRIPT" | tee -a "$LOG"
echo "Log: $LOG"
echo ""
echo "Next: open Unity, let it reimport, verify no compile errors in the kept files."
